export const animeStamps = [
  {
    id: 'your-name',
    name: 'Your Name.',
    line: 'FILM',
    category: 'Anime & manga',
    note: 'A film by Makoto Shinkai.',
    href: 'https://gkids.com/films/your-name/',
  },
  {
    id: 'weathering-with-you',
    name: 'Weathering With You',
    line: 'FILM',
    category: 'Anime & manga',
    note: 'Rainy Tokyo, with a little weather magic.',
    href: 'https://gkids.com/films/weathering-with-you/',
  },
  {
    id: 'suzume',
    name: 'Suzume',
    line: 'FILM',
    category: 'Anime & manga',
    note: 'A journey through mysterious doors across Japan.',
    href: 'https://www.crunchyroll.com/series/GP5HJ8425/suzume',
  },
  {
    id: 'mushoku-tensei',
    name: 'Mushoku Tensei',
    line: 'SERIES',
    category: 'Anime & manga',
    note: 'Mushoku Tensei: Jobless Reincarnation.',
    href: 'https://www.crunchyroll.com/series/G24H1N3MP',
  },
  {
    id: 'kaiju-no-8',
    name: 'Kaiju No. 8',
    line: 'ANIME / MANGA',
    category: 'Anime & manga',
    note: 'Kafka Hibino and the Japan Defense Force.',
    href: 'https://www.viz.com/kaiju-no-8',
  },
  {
    id: 'dandadan',
    name: 'Dandadan',
    line: 'ANIME / MANGA',
    category: 'Anime & manga',
    note: 'Aliens, ghosts, Momo and Okarun.',
    href: 'https://www.viz.com/dandadan',
  },
  {
    id: 'noragami',
    name: 'Noragami',
    line: 'ANIME / MANGA',
    category: 'Anime & manga',
    note: 'Noragami: Stray God.',
    href: 'https://kodansha.us/series/noragami-stray-god/',
  },
  {
    id: 'villager-level-999',
    name: 'The Villager of Level 999',
    line: 'SERIES',
    category: 'Anime & manga',
    note: 'A level 999 villager in a world of fixed roles.',
    href: 'https://www.crunchyroll.com/series/GT00371878',
  },
  {
    id: 'a-condition-called-love',
    name: 'A Condition Called Love',
    line: 'ANIME / MANGA',
    category: 'Anime & manga',
    note: 'A school romance by Megumi Morino.',
    href: 'https://kodansha.us/series/a-condition-called-love/',
  },
  {
    id: 'trapped-in-a-dating-sim',
    name: 'Trapped in a Dating Sim',
    line: 'SERIES',
    category: 'Anime & manga',
    note: 'Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs.',
    href: 'https://www.crunchyroll.com/series/G0XHWM0D3/trapped-in-a-dating-sim-the-world-of-otome-games-is-tough-for-mobs',
  },
  {
    id: 'daemons-of-the-shadow-realm',
    name: 'Daemons of the Shadow Realm',
    line: 'SERIES',
    category: 'Anime & manga',
    note: 'Supernatural fantasy by Hiromu Arakawa.',
    href: 'https://squareenixmangaandbooks.square-enix-games.com/en-us/series/daemons-of-the-shadow-realm',
  },
] as const;
