import { animeStamps } from '@/lib/anime-stamps';

export const stampCategories = [
  'All stamps',
  'Anime & manga',
  'Apps',
  'Toolkit',
  'Interests',
] as const;

export const stamps = [
  {
    id: 'discord',
    name: 'Discord',
    line: 'BOT TERRITORY',
    category: 'Apps',
    note: 'Where most of my bots live.',
    href: 'https://discord.com/',
  },
  {
    id: 'github',
    name: 'GitHub',
    line: 'CODE LIVES HERE',
    category: 'Apps',
    note: 'Projects, forks, and unfinished ideas.',
    href: 'https://github.com/devrock07',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    line: 'ZENITHSENPAI',
    category: 'Apps',
    note: 'My other corner of the internet.',
    href: 'https://www.youtube.com/@ZenithSenpai',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    line: '@D4VROCK',
    category: 'Apps',
    note: 'Find me as d4vrock.',
    href: 'https://www.instagram.com/d4vrock/',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    line: 'MAKE IT WORK',
    category: 'Toolkit',
    note: 'Web tools and Discord bots.',
    href: '/projects#pogy-bot',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    line: 'TYPE CHECKED',
    category: 'Toolkit',
    note: 'A little order in the code.',
    href: '/projects#animc',
  },
  {
    id: 'python',
    name: 'Python',
    line: 'AUTOMATE IT',
    category: 'Toolkit',
    note: 'Scripts, utilities, and REM-AIO.',
    href: '/projects#rem-aio',
  },
  {
    id: 'node',
    name: 'Node.js',
    line: 'SERVER SIDE',
    category: 'Toolkit',
    note: 'The runtime behind many of my bots.',
    href: 'https://nodejs.org/en',
  },
  {
    id: 'svelte',
    name: 'Svelte',
    line: 'WEB INTERFACES',
    category: 'Toolkit',
    note: 'Used to build AniMc.',
    href: 'https://svelte.dev/',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    line: 'BLOCK BY BLOCK',
    category: 'Interests',
    note: 'Skins and pixel mascots with AniMc.',
    href: '/projects#animc',
  },
  {
    id: 'pixels',
    name: 'Pixel art',
    line: 'PIXEL BY PIXEL',
    category: 'Interests',
    note: 'Draw a little something on the site.',
    href: '/#pixel-pad',
  },
  {
    id: 'source',
    name: 'Open source',
    line: 'READ THE SOURCE',
    category: 'Interests',
    note: 'The code stays out in the open.',
    href: 'https://github.com/devrock07',
  },
  ...animeStamps,
] as const;

export type Stamp = (typeof stamps)[number];
